mqtt:
  broker:
    host: "localhost"                       # MQTTサーバーのアドレス
    port: 1883                              # MQTTサーバーのポート番号
    client_id: "vehicle_camera_01"          # アプリの名称、MQTTを区別できるように、名称は異なるが必要
    infer_before_topic: "infer_yolov8_02"   # 推論必要なデータはここに送信する

camera:
  source:
    url: "videos/vehicle_camera_02.mp4"   # ファイル名、またはRTSP、RTMP先
    width: 400                            # 送信された画像の幅さ
    height: 400                           # 送信された画像の高さ
    fps: 10                               # 送信された画像のFPS

  record:
    enable: False                         # ビデオを保存するかどうか
    filename: "record"                    # 生成されたファイル名
  
  preprocess:
    enable: False                         # 送信前、画像を調整するかどうか
    gamma: 1.0                            # gamma
    contrast: 1.0                         # constrast
    brightness: 0.0                       # brightness
    colorspace: "bgr"                     # color space
  
debug_mode: False                         # If True, the image will be displayed in the window
